name: mac-build
on:
  push:
    branches: [ "8.1.x-5.x" ]
    tags:
      - 8.1.*-5.*-r*

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Static Build
        id: cache-static-deps
        uses: actions/cache@v3
        with:
          path: |
            ./opt
            ./pool
            ./thirdparty
          key: ${{ runner.os }}-8.1.x-5.x-static-deps
      - name: init deps
        run: |
          mkdir -p pool/lib pool/ext thirdparty opt
          ln -s ${{ github.workspace }}/opt ${{ github.workspace }}/../
          ./prepare.php macos ${{ github.workspace }}/..
          chmod +x make.sh
          brew uninstall --ignore-dependencies oniguruma brotli freetype libomp snappy zstd
          ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
          brew install bison automake re2c
          rm -rf ../opt/usr/lib/*.dylib
      - if: ${{ steps.cache-static-deps.outputs.cache-hit != 'true' }}
        name: build deps
        run: |
          wget https://sourceforge.net/p/giflib/bugs/_discuss/thread/4e811ad29b/c323/attachment/Makefile.patch -O pool/lib/giflib.patch
          ./make.sh all-library
          rm -rf ../opt/usr/lib/*.dylib
      - name: make configure
        run: |
          ls -al ../opt/
          PATH="/usr/local/opt/bison/bin:$PATH" ./make.sh pkg-check
          PATH="/usr/local/opt/bison/bin:$PATH" ./make.sh config
          sed -i '' 's/-ne //g' ./main/php_config.h
      - name: make build
        run: |
          PATH="/usr/local/opt/bison/bin:$PATH" ./make.sh build
      - name: test
        run: |
          otool -L ./bin/swoole-cli
          ./bin/swoole-cli --version
          ./bin/swoole-cli -ini
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: swoole-cli-macos-${{ github.sha }}
          path: |
            bin
          retention-days: 5
      - if: startsWith(github.event.ref, 'refs/tags')
        name: compress binrary
        run: |
          cd bin
          gtar -cJvf swoole-cli-${{ github.sha }}.tar.xz swoole-cli LICENSE
          mv swoole-cli-${{ github.sha }}.tar.xz ../swoole-cli-macos.x64-${{ github.ref_name }}.tar.xz
      - if: startsWith(github.event.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        name: Upload binaries to release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: swoole-cli-macos.x64-${{ github.ref_name }}.tar.xz
          tag: ${{ github.ref }}